#ifndef CONSTANTS_H
#define CONSTANTS_H

#define FPS 60.0

#define DEBUG_MODE false

#define SCREEN_WIDTH 900
#define SCREEN_HEIGHT 450

#define BACKGROUND_WIDTH 1200
#define BACKGROUND_HEIGHT 600

#define MISSILE_SRC_WIDTH 25
#define MISSILE_SRC_HEIGHT 25
#define MISSILE_DST_WIDTH 35
#define MISSILE_DST_HEIGHT 35

#define LAUNCHER_SRC_WIDTH 152
#define LAUNCHER_SRC_HEIGHT 214
#define LAUNCHER_DST_WIDTH 114
#define LAUNCHER_DST_HEIGHT 161

#define MAX_HIGHSCORES 4
#define MISSILES 4
#define LEVEL_SIZE 8

#define LAUNCH_STRENGTH 8
#define GRAVITYCONSTANT 15
#define AIRFRICTIONCONSTANT 1.003
#define VELOCITYPRESCALER 100

#define HITDURATION 15
#define TARGETANIMTIMING 40

#endif