#ifndef SPRITE_H
#define SPRITE_H

enum Sprite {
    SPRT_BACKGROUND,
    SPRT_MENU_BACKGROUND,
    SPRT_MISSILE_1,
    SPRT_MISSILE_2,
    SPRT_MISSILE_3,
    SPRT_TARGET,
    SPRT_TARGET_HIT,
    SPRT_STONE,
    SPRT_STONE_HIT,
    SPRT_BOX,
    SPRT_BOX_HIT,
    SPRT_LAUNCHER,

    SPRT_CSTONE,
    SPRT_CSTONE_HIT,
    SPRT_FIRECHARGE,
    SPRT_OBSIDIAN,
    SPRT_OBSIDIAN_HIT,
    SPRT_SLIME1,
    SPRT_SLIME2,
    SPRT_SLIME_HIT,
    SPRT_BEE1,
    SPRT_BEE2,
    SPRT_BEE3,
    SPRT_ROCK,
    SPRT_EXPLOSION1,
    SPRT_EXPLOSION2,
    SPRT_EXPLOSION3,
    SPRT_EXPLOSION4,
    SPRT_EXPLOSION5,
    SPRT_LENGTH
};

#endif